[package]
name = "KADE_NETWORK"
version = "1.0.0"
authors = []

[addresses]
kade="0x809001fa9030e21dbe72a45291ddf227610e9c228025c8d93670ddd894f4141d"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-token-objects/"
rev = "mainnet"

[dev-dependencies]
